# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
    # add any other tools you need for your project build

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
    
# Skip the installation of dependencies during build
# since mariadb-connector-c is not available on PyPI
install:
  - skip: true
